# Imports

In [1]:
import pandas as pd
import requests
import nbimporter
from nbimporter import NotebookLoader

loader = NotebookLoader('.')
module = loader.load_module('data_scraping_functions')

from data_scraping_functions import scraping_data_open_and_games

# Definitions

In [2]:
year = 2014
competition = "open"
base_path = "C:/Users/Zi/Documents/data-science-crossfit/"

# Data Scraping

In [3]:
# Scrape data for the 'open' competition and the current year
df_open_year = scraping_data_open_and_games(year, competition)
# Add a new column 'genderId' with the value of 'divisionId' for consistency
df_open_year['genderId'] = df_open_year['divisionId']
# Drop irrelevant columns
df_open_year = df_open_year.drop(columns=['postCompStatus', 'profilePicS3key', 'countryShortCode', 'teamCaptain', 'divisionId'])
# Add a new column 'year' with the current year
df_open_year['year'] = year
# Print the consolidated DataFrame
df_open_year

,competitorId,competitorName,firstName,lastName,status,gender,countryOfOriginCode,countryOfOriginName,regionId,regionName,affiliateId,affiliateName,age,height,weight,overallRank,overallScore,genderId,year
0,11435,Rich Froning,Rich,Froning,ACT,M,,,6,Central East,3220,CrossFit Mayhem,26,,,1,18,1,2014
1,12485,Jason Khalipa,Jason,Khalipa,ACT,M,,,12,Northern California,2605,,28,,,2,72,1,2014
2,43761,Ben Smith,Ben,Smith,ACT,M,,,9,Mid Atlantic,4933,CrossFit Krypton,24,,,3,92,1,2014
3,47661,Dan Bailey,Dan,Bailey,ACT,M,,,16,Southern California,0,,30,,,4,122,1,2014
4,34796,Scott Panchik,Scott,Panchik,ACT,M,,,6,Central East,7991,CrossFit Mentality,26,,,5,157,1,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132355,318390,Annie Modica,Annie,Modica,ACT,F,,,11,North East,5565,,24,,,ACT,0,2,2014
132356,270521,Jennifer Swentek,Jennifer,Swentek,ACT,F,,,16,Southern California,2957,,33,,,ACT,0,2,2014
132357,284402,Megan Buskey,Megan,Buskey,ACT,F,,,9,Mid Atlantic,791,CrossFit DC,32,,,ACT,0,2,2014
132358,383768,Erica Frederick,Erica,Frederick,ACT,F,,,15,South East,6875,,32,,,ACT,0,2,2014
132359,285539,Kathleen Menchetti,Kathleen,Menchetti,ACT,F,,,9,Mid Atlantic,7255,,42,,,ACT,0,13,2014

# Exports

In [5]:
df_open_year.to_csv(base_path + "csv_files/version_1_raw_data/df_open_" + str(year) + ".csv", index=False)