# Imports

In [1]:
import pandas as pd
import os

# Definitions

In [2]:
base_path = "C:/Users/Zi/Documents/data-science-crossfit/"

# Data Cleaning

### Games

In [3]:
df_games_conso = pd.read_csv(base_path + "csv_files/version_1_raw_data/df_games_conso.csv")

df_games_conso.loc[df_games_conso['countryOfOriginName'] == 'Namibia', 'countryOfOriginCode'] = 'NA'

df_games_conso.loc[df_games_conso['countryOfOriginCode'] == 'BY', 'countryOfOriginName'] = 'Belarus'

df_games_conso.loc[df_games_conso['countryOfOriginCode'] == 'RU', 'countryOfOriginName'] = 'Federation'

In [4]:
df_games_conso

,competitorId,competitorName,firstName,lastName,status,gender,countryOfOriginCode,countryOfOriginName,regionId,regionName,affiliateId,affiliateName,age,height,weight,overallRank,overallScore,genderId,year
0,164070,James Fitzgerald,James,Fitzgerald,ACT,M,NaN,NaN,NaN,NaN,NaN,NaN,33,69 in,176 lb,1,272,1,2007
1,57785,Brett Marshall,Brett,Marshall,ACT,M,NaN,NaN,NaN,NaN,NaN,NaN,33,168 cm,155 lb,2,270,1,2007
2,10091,Josh Everett,Josh,Everett,ACT,M,NaN,NaN,NaN,NaN,NaN,NaN,32,69 in,185 lb,3,267,1,2007
3,27065,Chris Spealler,Chris,Spealler,ACT,M,NaN,NaN,NaN,NaN,NaN,NaN,28,65 in,143 lb,4,261,1,2007
4,7173,Breck Berry,Breck,Berry,ACT,M,NaN,NaN,NaN,NaN,NaN,NaN,31,67 in,170 lb,5,252,1,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1709,1547449,Emma Cary,Emma,Cary,ACT,F,US,United States,35.0,North America East,1893.0,CrossFit Naples,19,64 in,140 lb,0,0,2,2023
1710,1931423,Emma Lawson,Emma,Lawson,ACT,F,CA,Canada,35.0,North America East,21726.0,CrossFit PSC,18,65 in,140 lb,0,0,2,2023
1711,1983424,Elisa Fuliano,Elisa,Fuliano,ACT,F,IT,Italy,29.0,Europe,16895.0,CrossFit Altessano,27,157 cm,60 kg,0,0,2,2023
1712,2012971,Alexia Williams,Alexia,Williams,ACT,F,AR,Argentina,33.0,South America,31497.0,WTC CrossFit,24,169 cm,70 kg,0,0,2,2023
1713,2077209,Abigail Domit,Abigail,Domit,ACT,F,US,United States,34.0,North America West,770.0,Lone Star CrossFit,25,67 in,147 lb,0,0,2,2023

In [5]:
df_games_conso.isnull().sum()

competitorId             0
competitorName           0
firstName                0
lastName                 1
status                   0
gender                   0
countryOfOriginCode    723
countryOfOriginName    723
regionId               886
regionName             886
affiliateId            802
affiliateName          802
age                      0
height                 169
weight                 164
overallRank              0
overallScore             0
genderId                 0
year                     0
dtype: int64

In [6]:
# Group by 'countryOfOriginName' and count the number of unique 'regionName' values for each country
region_counts = df_games_conso.groupby('countryOfOriginName')['regionName'].nunique()

# Filter countries with two or more unique 'regionName' values
countries_with_multiple_regions = region_counts[region_counts >= 2]

# Print the result
countries_with_multiple_regions

countryOfOriginName
Australia                3
Canada                   7
Federation               2
Finland                  2
France                   2
Germany                  2
Hungary                  2
Iceland                  4
New Zealand              3
Norway                   2
Sweden                   2
Switzerland              2
United Arab Emirates     3
United States           14
Name: regionName, dtype: int64

In [7]:
# Filter the DataFrame to include only rows where 'countryOfOriginName' is 'Australia'
australia_df = df_games_conso[df_games_conso['countryOfOriginName'] == 'Iceland']

# Get the different values of 'regionName' for Australia
unique_regions_australia = australia_df['regionName'].unique()

# Print the result
unique_regions_australia

array([nan, 'Europe', 'Central East', 'North East', 'Europe North'],
      dtype=object)

In [8]:
df = df_games_conso[(df_games_conso['countryOfOriginName'].notnull()) & (df_games_conso['regionName'].isnull())]

df

# df['countryOfOriginName'].unique()

,competitorId,competitorName,firstName,lastName,status,gender,countryOfOriginCode,countryOfOriginName,regionId,regionName,affiliateId,affiliateName,age,height,weight,overallRank,overallScore,genderId,year
455,11435,Rich Froning,Rich,Froning,ACT,M,US,United States,NaN,NaN,NaN,NaN,23,69 in,194 lb,1,856,1,2011
456,3180,Joshua Bridges,Joshua,Bridges,ACT,M,US,United States,NaN,NaN,NaN,NaN,28,71 in,215 lb,2,763,1,2011
457,43761,Ben Smith,Ben,Smith,ACT,M,US,United States,NaN,NaN,NaN,NaN,21,71 in,195 lb,3,738,1,2011
458,11451,Graham Holmberg,Graham,Holmberg,ACT,M,US,United States,NaN,NaN,NaN,NaN,26,71 in,190 lb,4,717,1,2011
459,4158,Blair Morrison,Blair,Morrison,ACT,M,US,United States,NaN,NaN,NaN,NaN,29,72 in,190 lb,5,708,1,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,1018713,Laura Clifton,Laura,Clifton,ACT,F,NZ,New Zealand,NaN,NaN,NaN,NaN,26,162 cm,75 kg,26,0,2,2020
1469,466656,Andrea Solberg,Andrea,Solberg,ACT,F,NO,Norway,NaN,NaN,21180.0,InnerLimit CrossFit,24,164 cm,135 lb,27,0,2,2020
1470,2099,Harriet Roberts,Harriet,Roberts,ACT,F,NZ,New Zealand,NaN,NaN,2414.0,CrossFit Athletic,28,171 cm,149 lb,28,0,2,2020
1471,115239,Brooke Haas,Brooke,Haas,ACT,F,US,United States,NaN,NaN,9506.0,Crucible CrossFit,31,63 in,154 lb,29,0,2,2020
1472,534813,Sanna Venäläinen,Sanna,Venäläinen,ACT,F,FI,Finland,NaN,NaN,7232.0,CrossFit Vantaa,29,164 cm,64 kg,30,0,2,2020

In [9]:
column_values = df_games_conso['countryOfOriginCode'].unique()
sorted_column_values = sorted(map(str, column_values))

values_starting_with_R = [value for value in sorted_column_values if value.startswith('U')]
values_starting_with_R

['UA', 'US', 'UY']

### Open