# Imports

In [1]:
import pandas as pd
import requests
import nbimporter
from nbimporter import NotebookLoader

loader = NotebookLoader('.')
module = loader.load_module('data_scraping_functions')

from data_scraping_functions import scraping_data_open_and_games

# Definitions

In [2]:
years = range(2007, 2024)
competition = "games"
base_path = "C:/Users/Zi/Documents/data-science-crossfit/"

# Data Scraping

In [3]:
dataframes_list = []

# Iterate over each year
for year in years:
    # Scrape data for the 'games' competition and the current year
    df_games_year = scraping_data_open_and_games(year, competition)
    # Add a new column 'genderId' with the value of 'divisionId' for consistency
    df_games_year['genderId'] = df_games_year['divisionId']
    # Drop irrelevant columns
    df_games_year = df_games_year.drop(columns=['postCompStatus', 'profilePicS3key', 'countryShortCode', 'teamCaptain', 'divisionId'])
    # Add a new column 'year' with the current year
    df_games_year['year'] = year
    # Append the data for the current year to the combined list
    dataframes_list.append(df_games_year)
# Create a single DataFrame by concatenating the list of DataFrames
df_games_conso = pd.concat(dataframes_list)
# Print the consolidated DataFrame
df_games_conso

,competitorId,competitorName,firstName,lastName,status,gender,countryOfOriginCode,countryOfOriginName,regionId,regionName,affiliateId,affiliateName,age,height,weight,overallRank,overallScore,genderId,year
0,164070,James Fitzgerald,James,Fitzgerald,ACT,M,,,None,,None,,33,69 in,176 lb,1,272,1,2007
1,57785,Brett Marshall,Brett,Marshall,ACT,M,,,None,,None,,33,168 cm,155 lb,2,270,1,2007
2,10091,Josh Everett,Josh,Everett,ACT,M,,,None,,None,,32,69 in,185 lb,3,267,1,2007
3,27065,Chris Spealler,Chris,Spealler,ACT,M,,,None,,None,,28,65 in,143 lb,4,261,1,2007
4,7173,Breck Berry,Breck,Berry,ACT,M,,,None,,None,,31,67 in,170 lb,5,252,1,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,1547449,Emma Cary,Emma,Cary,ACT,F,US,United States,35,North America East,1893,CrossFit Naples,19,64 in,140 lb,0,0,2,2023
77,1931423,Emma Lawson,Emma,Lawson,ACT,F,CA,Canada,35,North America East,21726,CrossFit PSC,18,65 in,140 lb,0,0,2,2023
78,1983424,Elisa Fuliano,Elisa,Fuliano,ACT,F,IT,Italy,29,Europe,16895,CrossFit Altessano,27,157 cm,60 kg,0,0,2,2023
79,2012971,Alexia Williams,Alexia,Williams,ACT,F,AR,Argentina,33,South America,31497,WTC CrossFit,24,169 cm,70 kg,0,0,2,2023
80,2077209,Abigail Domit,Abigail,Domit,ACT,F,US,United States,34,North America West,770,Lone Star CrossFit,25,67 in,147 lb,0,0,2,2023

# Exports

In [4]:
df_games_conso.to_csv(base_path + "csv_files/version_1_raw_data/df_games_conso.csv", index=False)